remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Charles O. Smith
description: Writer, artist, dog lover, Southern expatriate
show_downloads: false
